### ISSUE TITLE
Add ability to provide blacklist file for subtests

### ISSUE THREAD

**Issue by sumnerevans** [matrix-org/complement#618] opened 2023-02-25 03:47 UTC
Currently, in order to create custom blacklists of subtests for a new homeserver, you need to add that homeserver to the `runtime` package. Creating whitelists is possible by creating a `-run` regex, but creating said regex is quite annoying.

This is awkward for homeservers that are either closed source or otherwise not ready for prime-time. For example, consider someone who is in the middle of writing a homeserver. They may want to use Complement as part of their integration test suite to test its compatibility with the matrix spec. Right now, they would have to fork Complement and add their homeserver to the list of supported homeservers, and add a ton of `SkipIf` statements everywhere and remove them as the implement more features.

Specifically for Beeper, we use Complement as part of the test suite for our closed-source [Hungryserv](https://github.com/sumnerevans/hungryserv-presentation) homeserver (an unfederated homeserver for bridge traffic), and we explicitly did not implement certain things such as room aliases. We have already whitelisted the set of top-level tests we want to run using a `-run` regex, but then we have to use our fork which added Hungryserv to the homeserver list in order to blacklist subtests. (We could just whitelist every single subtest we want to run, but that would mean that we would have to keep that list up-to-date when new tests get added to the suite, so a blacklist is significantly better for us.)

If implemented, this will allow the homeservers to keep their Complement test blacklists in their own source control rather than in a separate repository, and we can remove all of the `SkipIf`s from complement.

### Proposed solution

1. Add a way to specify a blacklist file. Probably using some sort of environment variable is the best option for this.
1. In every test, wrap the `*testing.T` struct so that every `t.Run` call calls `SkipIf`. (It seems like you cannot replace `*testing.T` in the top-level test.) I imagine something like this:

    ```
    type ComplementTesting struct {
        *testing.T
    }

    func WrapTesting(t *testing.T) ComplementTesting {
        if blacklist.Contains(t.Name()) {
            t.Skip()
        }
        return ComplementTesting{t}
    }

    func (c ComplementTesting) Run(name string, f func(t ComplementTesting)) {
        c.T.Run(name, func(t *testing.T) {
            t.Helper()
            if blacklist.Contains(t.Name()) {
                t.Skip()
            }
            f(t)
        })
    }

    func TestFoo(tt *testing.T) {
        t := WrapTesting(t)

        t.Run("first subtest", func(...) { ... })
    }
    ```

If this is of interest, I'd be happy to work on implementing it.

**Comment by kegsay** [comment] 2023-02-27 09:56
Duplicate of https://github.com/matrix-org/complement/issues/242

Conclusion is basically https://github.com/matrix-org/complement/issues/242#issuecomment-984022934

**Closed by kegsay** 2023-02-27 09:56 UTC
